### PR TITLE
feat(ds): describe "complete node loss" disaster recovery scenario

### PR DESCRIPTION
**Pull request by keynslug**

### CODE REVIEW

**Review by thalesmg — DISMISSED** [review]

**Review by zmstone — COMMENTED** [review]
Need a reference from https://docs.emqx.com/en/emqx/latest/dashboard/configuration.html#management
To this doc.

**Comment by zmstone** [comment]
@Meggielqk please help to translate

**Comment by keynslug** [comment]
> Need a reference from https://docs.emqx.com/en/emqx/latest/dashboard/configuration.html#management

Hm, are there DS management pane in the dashboard? I can only see some bits of durable sessions configuration.

**Comment by Meggielqk** [comment]
> > Need a reference from https://docs.emqx.com/en/emqx/latest/dashboard/configuration.html#management
> 
> Hm, are there DS management pane in the dashboard? I can only see some bits of durable sessions configuration.

yes, currently there is no DS management pane in the Dashboard. I added the Dashboard information to the "Durable Sessions Configuration" section though.

**Review by Meggielqk — APPROVED** [review]

**Pull request merged**
