### PR TITLE
more supported platforms for emqtt-bench

### PR DESCRIPTION
**Pull request by id**
- add Amazon Linux 2023, Debian 12 and macOS 12 (Apple Silicon) in the list of supported platforms
- fix some typos
- unify usage of `emqtt-bench` vs `emqtt_bench`: use former when referring to the tool as a whole, use latter when referring to the executable binary
- replace `10W / s` with `100k/s` in the English version
- remove Snowflake from Roadmap since it's not planned anymore

### CODE REVIEW

**Comment by Meggielqk** [comment]
> * add Amazon Linux 2023, Debian 12 and macOS 12 (Apple Silicon) in the list of supported platforms

@id , for the updates on the above item, do we also need to update the installation pages for these supported platforms in the opensource edition document? https://www.emqx.io/docs/en/v5.1/deploy/install.html

**Comment by id** [comment]
@Meggielqk yes, for sure. On it.

**Comment by id** [comment]
- renamed install-centos.md to install-rhel.md, and merged it with corresponding Amazon Linux page since the install steps are the same
- @Meggielqk could you help to update Chinese version of install-rhel.md?
- I think we need to move Amazon Linux distros under CentOS/RHEL on our downloads page https://www.emqx.io/downloads?os=CentOS

**Comment by Meggielqk** [comment]
I saw the Chinese version of install-rhel.md has already been updated?

**Comment by id** [comment]
@Meggielqk in the English version I moved this paragraph:
> The section below will take CentOS 8 as an example to illustrate how to download the latest version of EMQX. For other versions, please visit the [EMQX Deployment page](https://www.emqx.io/downloads?os=CentOS). 

to the "Install with tar.gz" section from previous place above "Install with rpm". Not sure if the Chinese version has the same problem.

**Comment by Meggielqk** [comment]
> @Meggielqk in the English version I moved this paragraph:
> 
> > The section below will take CentOS 8 as an example to illustrate how to download the latest version of EMQX. For other versions, please visit the [EMQX Deployment page](https://www.emqx.io/downloads?os=CentOS).
> 
> to the "Install with tar.gz" section from previous place above "Install with rpm". Not sure if the Chinese version has the same problem.

@id, there is already a paragraph under the "Install with Package" section, the same as the paragraph you moved.  If CentOS 8 is used as an example only for "tar.gz", then we should remove the paragraph under "Install with Package". However, if CentOS 8 is used as examples for both "rpm" and "tar.gz", it's better to remove the paragraph under "Install with tar.gz". 

In the Chinese version, the paragraph is under "Install with Package", so I suppose it applies to both "rpm" and "tar.gz'?

**Comment by id** [comment]
"Install with Package" and "Install with tar.gz" are on the same level of hierarchy. In the English version I added one more correction to have the same note about different architectures and CentOS 8 as an example in both sections.

**Comment by Meggielqk** [comment]
> "Install with Package" and "Install with tar.gz" are on the same level of hierarchy. In the English version I added one more correction to have the same note about different architectures and CentOS 8 as an example in both sections.

"Install with Package" (h2) is one level-higher than "Install with tar.gz" (h3). There is also "Install with rpm" under the "Install with Package". Maybe we should remove the level-2 heading "Install with Package" if it is unnecessary?

**Review by wivwiv — APPROVED** [review]

**Pull request merged**
