### PR TITLE
Update to latest master from upstream.

### PR DESCRIPTION
**Pull request by sstrigler**
Also contains changes from https://github.com/emqx/emqx/pull/10195

### CODE REVIEW

**Comment by zmstone** [comment]
@wivwiv is this enough ? or are there extra steps?

**Comment by wivwiv** [comment]
1. These 3 APIs are still not fixed:

```
GET /status
Serves as a health check for the node.  Returns a plain text response describing the status of the node.  This endpoint requires no authentication.<br/><br/>Returns status code 200 if the EMQX application is up and running, 503 otherwise.<br/>This API was introduced in v5.0.10.<br/>The GET `/status` endpoint (without the `/api/...` prefix) is also an alias to this endpoint and works in the same way.  This alias has been available since v5.0.0.

POST /exhook/{name}/move
Move the server.<br/>NOTE: The position should be


POST /configs_reset/{rootname} 
Reset the config entry specified by the query string parameter `conf_path`.<br/>- For a config entry that has default value, this resets it to the default value;<br/>- For a config entry that has no default value, an error 400 will be returned
```

2. Please provide a copy in `zh` language, and please upload them to `. /redocly` instead of `./swagger`.
```
redocly
├── ce-en.json
├── ce-zh.json
├── ee-en.json
└── ee-zh.json
```

**Comment by wivwiv** [comment]
With the help of chatgpt, I used this code to check the api title.  You can also use it to check `zh` file before you upload.
```python
import json
import os

swEN = open('./swagger.json').read()
swEN = json.loads(swEN)

for item in swEN['paths'].items():
    key, value = item
    for item2 in value.items():
        method, api = item2
        title = api.get('summary') or api.get('description')
        if '<br/>' in title:
            print({
                'method': method,
                'key': key,
                'title': title
            })
```

**Comment by sstrigler** [comment]
> 1. These 3 APIs are still not fixed:
> 

> ```
> POST /exhook/{name}/move
> Move the server.<br/>NOTE: The position should be
> ```

Oh, yes, this needs another PR merged first. I'll turn this one to Draft and come back with an update.

> 
>  2. Please provide a copy in `zh` language, and please upload them to `. /redocly` instead of `./swagger`.
> 
> ```
> redocly
> ├── ce-en.json
> ├── ce-zh.json
> ├── ee-en.json
> └── ee-zh.json
> ```

If this is the desired default procedure now, we should probably update `README.md` to reflect this.

**Comment by sstrigler** [comment]
Took a bit longer than expected. @wivwiv could you have another look please? I used your script from above to double check and it looked good. 

Also question remains, should we update the README?

**Comment by sstrigler** [comment]
Now with changes from https://emqx.atlassian.net/browse/EMQX-8507

**Comment by wivwiv** [comment]
This is the workflow for REST API document updates. Sorry for not replying to you earlier.

https://github.com/emqx/emqx-docs/pull/1783

The e5.0.2 has been updated, you can try this process in v5.0.22.

Notice: It should be updated **only after each release** to avoid the API being added to the documentation but not available in the product.

**Comment by wivwiv** [comment]
By the way, can we provide the CE/EE version info and the current version number in the `info` field?

image

**Comment by sstrigler** [comment]
PR updated.

Created a ticket to include CE/EE and exact version info: https://emqx.atlassian.net/browse/EMQX-9569

**Comment by id** [comment]
@sstrigler FYI

@LenaLenaPan why this PR has been closed without merge?

**Pull request closed without merging**
