### PR TITLE
feat(install): mention need for UTF-8 locale under Linux

### PR DESCRIPTION
**Pull request by keynslug**
Part of [EMQX-9961](https://emqx.atlassian.net/browse/EMQX-9961).

### CODE REVIEW

**Comment by zmstone** [comment]
@Meggielqk  please help to add zh translations.

**Comment by wivwiv** [comment]
Is this a required operation for most OS?
If it is a rarely encountered problem, this section should be put in `install.md` ( let @Meggielqk move the content). 
This will avoid putting too much mental burden on the user.
EMQX can be started in the quickest way possible

--------------
@zmstone 
By the way, if this is a required operation, can this operation be dispensed with in other ways? For example, setting environment variables in `. /bin/emqx` to set the environment variable.

**Comment by zmstone** [comment]
> Is this a required operation for most OS? If it is a rarely encountered problem, this section should be put in `install.md` ( let @Meggielqk move the content). This will avoid putting too much mental burden on the user. EMQX can be started in the quickest way possible
> 
> @zmstone By the way, if this is a required operation, can this operation be dispensed with in other ways? For example, setting environment variables in `. /bin/emqx` to set the environment variable.

I would not recommend setting it in application level.
Because users will need to list, view, and even inspect the files uploaded to EMQX or generated by EMQX.

**Comment by keynslug** [comment]
@wivwiv 

> If it is a rarely encountered problem

I believe that nowadays it is, though this depends on distribution in use.

> this section should be put in `install.md`

Wanted to point out that stuff in this PR is Linux-specific.

**Review by wivwiv — DISMISSED** [review]

**Review by Meggielqk — APPROVED** [review]

**Pull request merged**
