### PR TITLE
doc(shared): local strategy and per-group

### PR DESCRIPTION
**Pull request by gsychev**
https://github.com/emqx/emqx/pull/7462

### CODE REVIEW

**Comment by hjianbo** [comment]
Is it should merge to release-4.3 first? In this way, it will also be automatically synced to the release-4.4

**Review by zmstone — CHANGES_REQUESTED** [review]
This PR should be sent to release-4.3 and synced to release-4.4

**Comment by zmstone** [comment]
@gsychev please rebase on to release-4.3
changing the merge base will bring all 4.4 changes back to 4.3.

**Comment by gsychev** [comment]
Closed in favor of #1113

**Pull request closed without merging**
